import sys
from pathlib import Path
from numpy.typing import NDArray
import numpy as np
import random

# Add parent directories to access ga module
sys.path.insert(0, str(Path(__file__).parent.parent.parent))

from ga.custom_types import Gait
from ga.target_sol import produce_target
from ga.custom_types import *



def generate_training_data(gait_length:int = 1000,period:Period = 0.2,coxa_amp:float = 20,tibia_femur_v_shift:float=45,tibia_femur_amplitude:float=25) -> tuple[Gait,Gait]:
    """
    Generates training data to feed the NN
    Generates a gait, then splits input(N) and then output(N+1)
    Parameters:
        gait_length (int): The number of frames the gait will be generated for
    Returns:
        tuple with input data and output data, same indexes correspond to input and labeled output
    """

    # generate target gait
    total_gait:Gait = produce_target(gait_length,period,coxa_amp,tibia_femur_v_shift,tibia_femur_amplitude)

    # normalize data between 0 and 1
    # actual range: coxa [-23, 23], tibia-femur approximately [-75, -20]
    # use range [-80, 30] to be safe (110 total range)
    for i in range(len(total_gait)):
        # normalize each joint value
        for j in range(len(total_gait[i])):
            total_gait[i][j] = (total_gait[i][j] + 80) / 110
    # split into input and output data
    inputs:list[list[float]] = []
    outputs:list[list[float]] = []

    # generate input output pairs
    # gait_length -1 because output is N+1
    for i in range(gait_length -1):
        inputs.append(total_gait[i])
        outputs.append(total_gait[i+1])
    return (inputs,outputs)


def shuffle_data(input:list,label:list) -> tuple[NDArray,NDArray]:
    """
    Shuffles input and label data in the same order
    Parameters:
        input (list): Input data
        label (list): Label data
    Returns:
        Shuffled input and label data as numpy arrays
    """
    # generate permutated indexes
    permutated_idxs:NDArray = np.random.permutation(len(input))
    # apply to input and label
    shuffled_in, shuffled_label = np.array(input)[permutated_idxs],np.array(label)[permutated_idxs]
    return (shuffled_in,shuffled_label)

def generate_train_test_data(train_ratio:float = 0.8,data_points:int=30,variations:int=1) -> dict[str:tuple[Gait,Gait]]:
    """
    Generates training and test data to train NN
    Parameters:
        train_ratio (float): Value between 0 - 1, to specify the ratio of data points to be used as training and test data, this value corresponds to the training data amount. so a 0.8 will result in 80% of the data being used for training.
        data_points (int): Value which specifies how much data should be generated by target solution function, this is essentially how long the gait should be.
        variations (int): Number of gait variations for training data
    Returns:
        A dictionary which contains the training data and test data. The values are (input,label). Keys are "training","test"
    """

    # initialize empty lists
    input: Gait = []
    label: Gait = []
    
    # generate variations of gait data
    for _ in range(variations):
        # randomize gait parameters with wider ranges for better generalization
        period:float = round(random.uniform(0.1, 1), 3)
        c_amp = round(random.uniform(15, 23), 3)
        tibia_femur_v_shift = round(random.uniform(40, 55), 3)
        tibia_femur_amplitude = round(random.uniform(15, 35), 3)

        # generate training data for each variation
        _input, _label = generate_training_data(data_points,period,c_amp,tibia_femur_v_shift,tibia_femur_amplitude)
        input = input + _input
        label = label + _label

    # determine slicing index
    slice_idx:int = round((data_points*variations) * train_ratio)
    # shuffle data
    input,label = shuffle_data(input,label)

    # create data dictionary to hold training and test data
    data:dict[str: tuple[Gait,Gait]] = {"training":(),"test":()}
    # slice and convert to numpy array
    data["training"] = (np.array(input[0:slice_idx]), np.array(label[0:slice_idx]))
    data["test"] = (np.array(input[slice_idx:]), np.array(label[slice_idx:]))

    return data
