from custom_types import Gait
import numpy as np
from target_sol import produce_target

def generate_training_data(gait_length:int = 1000) -> tuple[Gait,Gait]:
    """
    Generates training data to feed the NN
    Generates a gait, then splits input(N) and then output(N+1)
    Parameters:
        gait_length (int): The number of frames the gait will be generated for
    Returns:
        tuple with input data and output data, same indexes correspond to input and labeled output
    """
    total_gait:Gait = produce_target(gait_length,0.2,20,45,25)
    inputs:list[list[float]] = []
    outputs:list[list[float]] = []
    for i in range(gait_length -1):
        # need to be -1 since output is N+1
        inputs.append(total_gait[i])
        outputs.append(total_gait[i+1])
    return (inputs,outputs)

def generate_train_test_data(train_ratio:float = 0.8,data_points:int=1000) -> dict[str:tuple[Gait,Gait]]:
    """
    Generates training and test data to train NN
    Parameters:
        train_ratio (float): Value between 0 - 1, to specify the ratio of data points to be used as training and test data, this value corresponds to the training data amount. so a 0.8 will result in 80% of the data being used for training.
        data_points (int): Value which specifies how much data should be generated by target solution function, this is essentially how long the gait should be.
    Returns:
        A dictionary which contains the training data and test data. The values are (input,label). Keys are "training","test"
    """
    #TODO: need to add a way of randomizing training data, this should be pretty easy to do, just need to generate other gaits with diff amp and stuff. but probbaly keep the peroid the same.
    #TODO: we can also maybe add another parameter to this function such as gait variations? which would specify different gait walk cycles and such. e.g. 2 would generate 2 variations of gait like specified above? so changing amp and off set stuff
    input, label = generate_training_data(data_points)
    slice_idx:int = round(data_points * train_ratio)

    #TODO: make this type actually represent the np.array thing
    data:dict[str: tuple[Gait,Gait]] = {"training":(),"test":()}
    # slice and convert to numpy array
    data["training"] = (np.array(input[:slice_idx]), np.array(label[:slice_idx]))
    data["test"] = (np.array(input[slice_idx:]), np.array(label[slice_idx:]))
    return data
